// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5zGWgf6BMQODGeqanv7KGeHlx2QqtNfM',
    appId: '1:64793288797:web:bce0149064324a9d286db4',
    messagingSenderId: '64793288797',
    projectId: 'zeepalmtodoapp',
    authDomain: 'zeepalmtodoapp.firebaseapp.com',
    storageBucket: 'zeepalmtodoapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWdI_-vilaiJqfiFrL7l8sphlxqEgV06o',
    appId: '1:64793288797:android:18ed8966fb71fe09286db4',
    messagingSenderId: '64793288797',
    projectId: 'zeepalmtodoapp',
    storageBucket: 'zeepalmtodoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZlmifbISciMRG5Svwc1UdjKUKhpLefFQ',
    appId: '1:64793288797:ios:bff9558a2de0e183286db4',
    messagingSenderId: '64793288797',
    projectId: 'zeepalmtodoapp',
    storageBucket: 'zeepalmtodoapp.appspot.com',
    iosBundleId: 'com.example.haztechTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZlmifbISciMRG5Svwc1UdjKUKhpLefFQ',
    appId: '1:64793288797:ios:bff9558a2de0e183286db4',
    messagingSenderId: '64793288797',
    projectId: 'zeepalmtodoapp',
    storageBucket: 'zeepalmtodoapp.appspot.com',
    iosBundleId: 'com.example.haztechTask',
  );
}
